vlib work

vlog base/bd.v
vlog base/mx2.v
vlog base/mxi2.v
vlog base/mx4.v
vlog base/mx8.v
vlog base/fd1q.v
vlog base/fd1e.v
vlog base/fd2.v
vlog base/fd2q.v
vlog base/fd2e.v
vlog base/fd4q.v
vlog base/fd4e.v
vlog base/ldp1.v
vlog base/ldp1q.v
vlog base/ldp2.v
vlog base/ldp2q.v
vlog base/fjk2.v
vlog base/ha1.v
vlog base/fa1.v
vlog base/lsra.v
vlog base/lsrb.v
vlog base/mag4.v
vlog base/fa4r.v

vlog tom/and10.v
vlog tom/and11.v
vlog tom/and12.v
vlog tom/nand14.v
vlog tom/nd9.v
vlog tom/nd11.v
vlog tom/creg11.v
vlog tom/fjkr.v
vlog tom/fdr.v
vlog tom/dncnts.v
vlog tom/upcnts.v
vlog tom/slatchr.v
vlog tom/slatch.v
vlog tom/slatchc.v
vlog tom/slatchp.v
vlog tom/stlatch.v
vlog tom/up.v
vlog tom/down.v
vlog tom/dec38h.v
vlog tom/dec38gh.v
vlog tom/dncnt.v
vlog tom/upcnt.v
vlog tom/udcnt.v
vlog tom/upcnt1.v
vlog tom/udcnt1.v
vlog tom/mag11.v
vlog tom/mag12.v
vlog tom/add4.v
vlog tom/sadd4.v
vlog tom/sadd8.v
vlog tom/ha9.v
vlog tom/twoniv.v

vlog tom/_graphics.v
vlog tom/iodec.v
vlog tom/vid.v
vlog tom/cryrgb.v
vlog tom/pix.v
vlog tom/dbus.v
vlog tom/bank.v
vlog tom/abus.v
vlog tom/arb.v
vlog tom/memwidth.v
vlog tom/bus.v
vlog tom/cpu.v
vlog tom/rasgen.v
vlog tom/mem.v
vlog tom/ack_pipe.v
vlog tom/ob.v
vlog tom/wbk.v
vlog tom/obdata.v
vlog tom/lbuf.v
vlog tom/misc.v

vlog tom/tom.v
vlog tb.v

vsim -t 1ns -lib work tb

